const SET_ACTOR_INFO = 'SET_ACTOR_INFO'
const LOAD_ACTOR_INFO = 'LOAD_ACTOR_INFO'
const SET_ACTOR_FILMOGRAPHY = 'SET_ACTOR_FILMOGRAPHY'
const LOAD_ACTOR_FILMOGRAPHY = 'LOAD_ACTOR_FILMOGRAPHY'
const SET_ACTOR_PHOTOS = 'SET_ACTOR_PHOTOS'
const LOAD_ACTOR_PHOTOS = 'LOAD_ACTOR_PHOTOS'
const SET_LOADING = "SET_LOADING";
const SET_LOADING_CAST = 'SET_LOADING_CAST'


export {
    SET_ACTOR_INFO,
    LOAD_ACTOR_INFO,
    SET_ACTOR_FILMOGRAPHY,
    LOAD_ACTOR_FILMOGRAPHY,
    SET_ACTOR_PHOTOS,
    LOAD_ACTOR_PHOTOS,
    SET_LOADING,
    SET_LOADING_CAST
}