const SET_MOVIES = 'SET_MOVIES'
const LOAD_MOVIES = 'LOAD_MOVIES'
const SET_SORT = 'SET_SORT'
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE'
const LOAD_SELECTED_MOVIE = 'LOAD_SELECTED_MOVIE'
const SET_GENRES = 'SET_GENRES'
const SET_SIMILAR_MOVIES = 'SET_SIMILAR_MOVIES'
const LOAD_SIMILAR_MOVIES = 'LOAD_SIMILAR_MOVIES'
const LOAD_MOVIE_TRAILER = 'LOAD_MOVIE_TRAILER'
const SET_MOVIE_TRAILER = 'SET_MOVIE_TRAILER'
const LOAD_SEARCH_RESULTS = 'LOAD_SEARCH_RESULTS'
const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
const LOAD_CAST = 'LOAD_CAST'
const SET_CAST = 'SET_CAST'


export {
    SET_MOVIES,
    LOAD_MOVIES,
    SET_SELECTED_MOVIE,
    LOAD_SELECTED_MOVIE,
    SET_SORT,
    SET_CURRENT_PAGE,
    SET_GENRES,
    SET_SIMILAR_MOVIES,
    LOAD_SIMILAR_MOVIES,
    LOAD_MOVIE_TRAILER,
    SET_MOVIE_TRAILER,
    LOAD_SEARCH_RESULTS,
    SET_SEARCH_RESULTS,
    LOAD_CAST,
    SET_CAST
}